### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mauron85** [hernantz/backbone.sos#2]
Correct me if I'm wrong, but when you start tracking model as in example

```
var MyModel = Backbone.Model.extend({
  initialize: function () {
    Backbone.SOS.track(this);
  }
});
```

when you destroy model, you have just leaked memory. As event listeners are not removed.

**Comment by hernantz** [comment]
@mauron85 that's a valid concern. 
I have not done any test to prove myself that `SOS` does not introduce memory leaks. I _think_ it doesn't.
If you look at the code, `SOS` does something like this:

``` js
var onRequest = function (obj) {
    obj.loading = true;
    obj.trigger("loading", obj);
};

SOS.track = function (obj, options) {
  obj.on("request", onRequest, obj);  // obj can be a model or a collection
}
```

So the `obj` is responsible for keeping track of the callback.
When you do a `model.destroy()`, backbone makes sure to unbind all callbacks from that model by doing `model.stopListening()`, and that would cover the unbinding of the `onRequest` callback.

I would like to have some empirical proof that this is as I say, or fix it otherwise.
Have you run into any memory leaks?

**Comment by mauron85** [comment]
Sorry, you're right (and I was wrong). You're listening for Backbone.Events and not DOM events this should cause no leak. Closing as not relevant.
